version: "3"

services:
  backend:
    image: ghcr.io/zkhan93/cscbalvid:latest
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    env_file:
      - .env
    ports:
      - 8066:80
