version: "3"

services:
  backend:
    build: ../backend
    entrypoint:
      [
        "uvicorn",
        "main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "80"
      ]
    env_file:
      - backend.env
    ports:
      - 8066:80
    restart: always

  web:
    build: ../frontend
    ports:
      - 8067:80
    restart: always

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - web
      - backend
