version: "3"

services:

  backend:
    image: ghcr.io/zkhan93/cscbalvid-backend:latest
    entrypoint:
      [
        "uvicorn",
        "main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "80"
      ]
    env_file:
      - backend.env
    restart: always

  web:
    image: ghcr.io/zkhan93/cscbalvid-web:latest
    restart: always

  proxy:
    image: nginxinc/nginx-unprivileged:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8066:80
    depends_on:
      - web
      - backend
    restart: always
